readlingual/apps/explorer/urls.py
from django.conf.urls import patterns, url

from readlingual.apps.explorer import views

urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    url(r'^(?P<work_id>\d+)/$', views.work, name='work'),
    url(r'^(?P<work_id>\d+)/(?P<worklanguage_id>\d+)/$', views.worklanguage, name='worklanguage'),
)

readlingual/apps/reader/urls.py
from django.conf.urls import patterns, url

from readlingual.apps.reader import views

urlpatterns = patterns('',
    # ex: /polls/
    url(r'^(?P<chapteroriginal_id>\d+)/(?P<chapter_id>\d+)/$', views.chapter, name='chapter'),
)

readlingual/urls.py
from django.conf.urls import patterns, include, url
from readlingual import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'LangText.views.home', name='home'),
    # url(r'^LangText/', include('LangText.foo.urls')),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^search', views.search, name='search'),
    url(r'^contact', views.contact, name='contact'),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^explorer/', include('readlingual.apps.explorer.urls')),
    url(r'^reader/', include('readlingual.apps.reader.urls')),
)

readlingual/apps/explorer/models.py
from django.db import models

class Language(models.Model):
    title = models.CharField(max_length=200)
    short_title = models.CharField(max_length=2)
    def __unicode__(self):
        return self.title

class Work(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    original_language = models.ForeignKey(Language)
    def __unicode__(self):
        return self.title

class WorkLanguage(models.Model):
    work = models.ForeignKey(Work)
    language = models.ForeignKey(Language)
    title = models.CharField(max_length=200)
    summary = models.TextField()
    def __unicode__(self):
        return self.title +"\\"+ self.language.short_title

readlingual/apps/reader/models.py
from django.db import models
from readlingual.apps.explorer.models import WorkLanguage

class Chapter(models.Model):
    work_language = models.ForeignKey(WorkLanguage)
    title = models.CharField(max_length=200)
    text = models.TextField()
    number = models.IntegerField()
    def __unicode__(self):
        return self.title

readlingual/apps/explorer/views.py
from django.shortcuts import render
from django.http import Http404

from readlingual.apps.explorer.models import Work, WorkLanguage
from readlingual.apps.reader.models import Chapter

def index(request):
    latest_work_list = Work.objects.all()[:5]
    context = {'latest_work_list': latest_work_list}
    return render(request, 'explorer/works.html', context)

def work(request, work_id):
    try:
        work = Work.objects.get(pk=work_id)
    except Work.DoesNotExist:
        raise Http404
    return render(request, 'explorer/work.html', {'work': work})

def worklanguage(request, work_id, worklanguage_id):
    try:
        worklanguage = WorkLanguage.objects.get(pk=worklanguage_id)
        work = Work.objects.get(pk=work_id)
        worklanguageoriginal = WorkLanguage.objects.get(language=work.original_language)
        worklanguageoriginal_chapters = Chapter.objects.filter(work_language=worklanguageoriginal.language).order_by('number')
        worklanguage_chapters = Chapter.objects.filter(work_language=worklanguage).order_by('number')
        chapters = zip(worklanguageoriginal_chapters, worklanguage_chapters)
    except Work.DoesNotExist:
        raise Http404
    return render(request, 'explorer/worklanguage.html', {'worklanguage_title': worklanguage.title, 'worklanguageoriginal_title': worklanguageoriginal.title, 'chapters': chapters,})

readlingual/apps/reader/views.py
from django.shortcuts import render
from django.http import Http404

from readlingual.apps.reader.models import Chapter

def chapter(request, chapteroriginal_id, chapter_id):
    try:
        chapter = Chapter.objects.get(pk=chapter_id)
        chapteroriginal = Chapter.objects.get(pk=chapteroriginal_id)
        chapter_paragraphs = zip(filter(None, chapteroriginal.text.splitlines()), filter(None, chapter.text.splitlines()))
    except Chapter.DoesNotExist:
        raise Http404
    return render(request, 'reader/chapter.html', {'chapter_paragraphs': chapter_paragraphs, 'chapteroriginal': chapteroriginal, 'chapter': chapter})

readlingual/views.py
from django.shortcuts import render_to_response, HttpResponseRedirect
from django.core.mail import send_mail
from django.core.validators import validate_email
from django.core.exceptions import ValidationError

def search(request):
    query = request.REQUEST.get("query", "")
    if query not in [None, '']:
        return HttpResponseRedirect("https://www.google.com/search?q="+query+"+site:readlingual.com");
    return render_to_response('search.html')

def contact(request):
    name = request.REQUEST.get("name", "")
    email = request.REQUEST.get("email", "")
    subject = request.REQUEST.get("subject", "")
    message = request.REQUEST.get("message", "")
    
    if name and email and subject and message:
        try:
            validate_email( email )
        except ValidationError:
            return render_to_response('contact.html', {'name':name,'email':email,'subject':subject,'message':message,'error_message': "Email is not correct"})
        
        send_mail(subject, name + ", " + message, email,['jakub.kociubinski@gmail.com'], fail_silently=False)
        
        return render_to_response('contact_success.html')
    else:
        if 'name' in request.GET:
            return render_to_response('contact.html', {'name':name,'email':email,'subject':subject,'message':message,'error_message': "some required fields are empty"})
        else:
            return render_to_response('contact.html')

readlingual/apps/explorer/templates/explorer/index.html
{% if latest_work_list %}
    <ul>
    {% for work in latest_work_list %}
        <li><a href="/explorer/{{ work.id }}/">{{ work.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No works are available.</p>
{% endif %}

readlingual/apps/explorer/templates/explorer/work.html
{% extends "base.html" %}

{% block title %}{{ work.title }}{% endblock %}

{% block subtitle %}{% endblock %}

{% block content %}
	<div class="5grid-layout">
		<ul>
		{% for worklanguage in work.worklanguage_set.all %}
			{% if worklanguage.language != work.original_language %}
				<li><b><a href="/explorer/{{ work.id }}/{{ worklanguage.id }}/">{{ worklanguage.title }} ({{ worklanguage.language }})</a></b></li>
			{% endif %}
		{% endfor %}
		</ul>
	</div>
{% endblock %}

readlingual/apps/explorer/templates/explorer/worklanguage.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block subtitle %}{% endblock %}

{% block content %}
	<div id="worklanguage">
		<table border="1">
		
			<tr class="worklanguageheader">
				<th>
					<h2>{{ worklanguageoriginal_title }}</h2>
				</th>
				<th>
					<h2>{{ worklanguage_title }}</h2>
				</th>
			</tr>
			
			{% for chapter_original, chapter_translated in chapters %}

				<tr class="box box-style1">
					<td>
	    				<a href="/reader/{{ chapter_original.id }}/{{ chapter_translated.id }}/">{{ chapter_original.title }}</a>
					</td>
					<td>
	    				<a href="/reader/{{ chapter_translated.id }}/{{ chapter_original.id }}/">{{ chapter_translated.title }}</a>
					</td>
				</tr>
			
			{% endfor %}

		</table>
	</div> 
{% endblock %}

readlingual/apps/explorer/templates/explorer/works.html
{% extends "base.html" %}

{% block title %}Works{% endblock %}

{% block subtitle %}Works page{% endblock %}

{% block content %}
		<div id="works">
			<div>
				{% for work in latest_work_list %}
					<div class="work">
						<article class="box box-style1">
							<a href="/explorer/{{ work.id }}" class="image image-full"><img src="static/images/portfolio01.jpg" alt="" /></a>
							<h3><a href="/explorer/{{ work.id }}">{{ work.title }}</a></h3>
							<p>{{ work.title }}</p>
						</article>
					</div>
			    {% endfor %}
			</div>
		</div>
{% endblock %}

readlingual/apps/reader/templates/reader/chapter.html
{% extends "base.html" %}

{% block js %}
<script src="{{ STATIC_URL }}js/jquery.qtip.min.js"></script>
<script src="{{ STATIC_URL }}js/wordlookup.js"></script>
{% endblock %}

{% block title %}{{ work.title }}{% endblock %}

{% block subtitle %}{% endblock %}

{% block content %}
	<div id="chapter">
		<table id="chapter-table">
		
		<tr>
			<th>
				<h2>{{ chapteroriginal.title }}</h2>
			</th>
			<th>
				<h2>{{ chapter.title }}</h2>
			</th>
		</tr>
		
		{% for paragraph_original, paragraph_translated in chapter_paragraphs %}
		<tr class="box box-style1">
			<td class="paragraf-original">
			    <p>{{ paragraph_original }}</p>
			</td>
			<td class="paragraf-translated">
			    <p>{{ paragraph_translated }}</p>
			</td>
		</tr>
		{% endfor %}
		
		</table>
	</div>
{% endblock %}

readlingual/templates/base.html
<!DOCTYPE HTML>
<html>
	<head>
		<title>Readlingual</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="Readlingual" />
		<meta name="keywords" content="Readlingual" />
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,600,700" rel="stylesheet" />
		<script src="/static/js/jquery-1.8.3.min.js"></script>
		<script src="/static/css/5grid/init.js?use=mobile,desktop,1000px"></script>
		<script src="/static/js/init.js"></script>
		{% block js %}{% endblock %}
		<noscript>
			<link rel="stylesheet" href="/static/css/5grid/core.css" />
			<link rel="stylesheet" href="/static/css/5grid/core-desktop.css" />
			<link rel="stylesheet" href="/static/css/5grid/core-1200px.css" />
			<link rel="stylesheet" href="/static/css/5grid/core-noscript.css" />
			<link rel="stylesheet" href="/static/css/style.css" />
			<link rel="stylesheet" href="/static/css/style-desktop.css" />
		</noscript>
		<!--[if lte IE 9]><link rel="stylesheet" href="/static/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="/static/css/ie8.css" /><![endif]-->
		<!--[if lte IE 7]><link rel="stylesheet" href="/static/css/ie7.css" /><![endif]-->
	</head>
	<body>

		<!-- Nav -->
			<nav id="nav">
				<ul>
					<li><a href="/">Home</a></li>
					<li><a href="/explorer">Works</a></li>
					<li><a href="/search">Search</a></li>
					<li><a href="/contact">Contact</a></li>
				</ul>
			</nav>

		<!-- Work -->
		
			<div class="wrapper wrapper-style3">
				<article id="work">
		
					<header>
						<h2>{% block title %}Readlingual{% endblock %}</h2>
						<span>{% block subtitle %}Free bilingual texts{% endblock %}</span>
					</header>
					{% block content %}
					<div class="5grid-layout">
						<div class="row">
							<div class="4u">
								<section class="box box-style1">
									<a class="main-link" href="/explorer">
									<span class="image image-centered"><img src="static/images/work01.png" alt="" /></span>
									<h3>Works</h3>
									</a>
									<p>A list of all available works.</p>
								</section>
							</div>
							<div class="4u">
								<section class="box box-style1">
									<a class="main-link" href="/search">
									<span class="image image-centered"><img src="static/images/work02.png" alt="" /></span>
									<h3>Search</h3>
									</a>
									<p>Search for a specific work.</p>
								</section>
							</div>
							<div class="4u">
								<section class="box box-style1">
									<a class="main-link" href="/contact">
									<span class="image image-centered"><img src="static/images/work03.png" alt="" /></span>
									<h3>Contact</h3>
									</a>
									<p>Contact us.</p>
								</section>
							</div>
						</div>
					</div>
					{% endblock %}
					<footer>
					</footer>
				</article>
			</div>
			
	</body>
</html>

readlingual/templates/contact.html
{% extends "base.html" %}

{% block title %}Send us a message!{% endblock %}

{% block subtitle %}This message will be send to our e-mail{% endblock %}

{% block content %}
	<div id="contact" class="5grid">
		<div class="row">
			<div class="12u">
				<form method="get">
					<div class="5grid">
						<div class="row">
							<div class="12u">
								<p id="bademail" class="error-message">{{error_message}}</p>
							</div>
						</div>
						<div class="row">
							<div class="6u">
								<input type="text" name="name" id="name" placeholder="Name" value="{{name}}" required/>
							</div>
							<div class="6u">
								<input type="text" name="email" id="email" placeholder="Email" value="{{email}}" required/>
							</div>
						</div>
						<div class="row">
							<div class="12u">
								<input type="text" name="subject" id="subject" placeholder="Subject" value="{{subject}}" required/>
							</div>
						</div>
						<div class="row">
							<div class="12u">
								<textarea name="message" id="message" placeholder="Message" required>{{message}}</textarea>
							</div>
						</div>
						<div class="row">
							<div class="12u">
								<input type="submit" class="button button-alt" value="Send" />
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

readlingual/templates/contact_success.html
{% extends "base.html" %}

{% block title %}Send us a message!{% endblock %}

{% block subtitle %}This message will be send to our e-mail{% endblock %}

{% block content %}
	<div id="contact" class="5grid">
		<div class="row">
			<div class="12u">
				<form method="get">
					<div class="5grid">
						<div class="row">
							<div class="12u">
								<p class="success-message">Your email has been successfully sent. Thank you.</p>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

readlingual/templates/index.html
{% extends "base.html" %}

readlingual/templates/search.html
{% extends "base.html" %}

{% block title %}Search{% endblock %}

{% block subtitle %}Search for works{% endblock %}

{% block content %}
	<form id="search" method="get">
		<div class="12u">
			<input type="text" name="query" id="query" placeholder="Search for..."></input>
		</div>
		<br />
		<div class="12u">
			<input type="submit" class="button button-alt" value="Search" />
		</div>
	</form>
	{% if result %}
		{% for (name, url, desc) in result %}
		<p>{{ name }}</p>
		<p>{{ url }}</p>
		<p>{{ desc }}</p>
	{% endfor %}
{% endif %}
{% endblock %}